### ISSUE TITLE
Resend forms tab

### ISSUE THREAD

**Issue by chanlawrencet** [JumboCode/South-Florida-Jewish-Academy#118]

**Comment by kianie413** [comment]
- similar to add student page (w/ two separate boxes)
- left box = check box w/ comment option material UI of forms (https://material-ui.com/components/lists/)
- name left box "select forms"
- when comment button is clicked, form is automatically checked
- right box = optional notes
- name right box = optional note
- bottom right button = "resend forms"
- at least 1 checkbox has to be selected in order to submit

**Comment by chanlawrencet** [comment]
Done with #143
